"""add outcomes table

Revision ID: 8576aaeb1071
Revises: 73d5b63c8fcf
Create Date: 2026-04-24 09:29:46.420113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8576aaeb1071'
down_revision: Union[str, None] = '73d5b63c8fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(), nullable=True),
    sa.Column('cover_letter_text', sa.Text(), nullable=True),
    sa.Column('jd_url', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    # ### end Alembic commands ###
